### ISSUE TITLE
Image render time

### ISSUE THREAD

**Issue by kirillDanshin** [rockchalkwushock/react-weather-app#4]
* [x] I have searched the
      [issues](https://github.com/rockchalkwushock/react-weather/issues) of this
      repository and believe that this is not a duplicate.

## Expected Behavior

images renders fast.

you should add a `link rel=preload`

## Current Behavior

"Oops! Something went wrong, please try again." bg image loads _sloooo.....................ooow_.

image already loaded and ready to be rendered

## Steps to Reproduce (for bugs)

Find a slow internet connection, like mine.
go to https://the-rising-sun.now.sh/

enter a zip that triggers "Oops! Something went wrong, please try again."
see that the image loads _sloooo.....................ooow_.

## Your Environment

| Tech            | Version |
| --------------- | ------- |
| `node`          |         |
| `npm` or `yarn` |         |
| `react-scripts` |         |
| OS              |         |
| Browser         |         |
| etc             |         |

**Comment by rockchalkwushock** [comment]
@kirillDanshin thanks for the feedback I will get this fixed this afternoon 👌

**Comment by rockchalkwushock** [comment]
I looked in an Incognito window in Chrome with a disabled cache and throttled using slow 3G option. You are definitely right on it being _sloooooooooooooow_!

![screen shot 2017-12-06 at 12 22 27](https://user-images.githubusercontent.com/19720404/33678502-8350528a-da81-11e7-8f1a-dd07256bb093.png)

I removed that static asset and instead am using a dynamic url from [Cloudinary](https://cloudinary.com/). Through this I can manipulate the quality, & format delivery of the image which will make for a much faster load time on slower networks and a slimmer data transfer foot print which will be better for mobile users.

![screen shot 2017-12-06 at 12 39 40](https://user-images.githubusercontent.com/19720404/33678821-94efd280-da82-11e7-8b38-db14d21eff25.png)

There seems to still be an issue with the `card-image` collapsing since there is no image initially in the space. I will have to look at what `materialize` is doing there and try to apply some initial height value.

**Comment by rockchalkwushock** [comment]
Seems I am still getting the collapsing issue when the image is not present yet. I will look into this more this evening.

**Comment by kirillDanshin** [comment]
checked it out. unfortunately, you've lost any quality. I think current solution is unacceptable. again, I propose you to add `link rel="prefetch"`. it will allow you to save the quality and fix this issue.

**Comment by rockchalkwushock** [comment]
@kirillDanshin ah I totally forgot to add that!

The quality is stepped down via a flag I passed on the Cloudinary url. I was using the _economy_ setting that steps down the quality significantly reducing the quality but also the data footprint of the image. I can step the quality back up on the image though.

I will roll out the fixes shortly, thank you again for taking the application for a test drive 👍

**Comment by rockchalkwushock** [comment]
I will look into this more this weekend. Seems to not be working quite right. Should be as easy as:

```html
<!--/public/index.html-->
<link rel="prefetch" href="%PUBLIC_URL%/images/rain.jpg">
```

```js
// ErrorView.js
...
<img alt="rain_404" className="responsive-img" src="/images/rain.jpg" />
...
```

I don't believe I need to be looking into any of the caches for a reference since `prefetch` is fetching the resource prior to navigation. I could be getting this and `preload` mixed up.

**Comment by rockchalkwushock** [comment]
@kirillDanshin 

I apologize for the delay on getting back to this.

I looked through the docs on `create-react-app` and found I was making a bit of a mistake with how I was handling the use of my image assets. By just placing them in the `public/` folder they were being copied over at build time to the `build/`. Updating the use of the images to the following lets `webpack` know these assets should be included in the bundle. Now the service worker can see these assets too so they are added to the `assets-manifest.json`.

Now when you visit the site the initial load time might be a bit slower; however the service worker will cache the `rain.jpg` and on the resulting 404 page the images load quite well. I tested in Incognito throttling over slow 3G.

I believe that will fix the issue, please let me know if you are still have the same issue. Thanks again for reporting this and taking the application for a test drive 🙌 

```js
// Inside ErrorView.js
import rain from '../assets/rain.jpg'

const ErrorView = () => {
...
<img alt="rain_404" className="responsive-img" src={rain} />
...
}
```

![screen shot 2017-12-16 at 06 47 55](https://user-images.githubusercontent.com/19720404/34070606-7ac40706-e22e-11e7-95ad-3910d3fe92eb.png)
